### ISSUE TITLE
Returned status code is not 200 on API call

### ISSUE THREAD

**Issue by jamogriff** [makeros3d/Octoprint-Makeros#4]
Issue where API call doesn't return status code 200 under "projects_index" command in __init__.py. Issue occurred before and after version 0.2.0 bump commit. Reinstalling using package manager and directly via pip did not solve issue.

### Localized code
![octoprint-error2](https://user-images.githubusercontent.com/7916354/99852865-16c6e680-2b3f-11eb-9109-2fe7700b8529.png)

### Front-end error message:
![octoprint-error](https://user-images.githubusercontent.com/7916354/99852860-129ac900-2b3f-11eb-88a5-a709b55b5791.png)

**Comment by makeros3d** [comment]
Hey @jamogriff I'm unable to replicate this issue on my instance.

In the else block that you've highlighted can you drop this code above the return:
```python
self._logger.error("status: {} / reason: {}".format(r.status_code, r.reason))
```

That should log out what is going on with the response. If you could send me that log on here I'll have an easier time of trying to figure out what is going on.

**Comment by makeros3d** [comment]
Marking this issue as resolved.
